import { Footer } from "@/components/loyout/footer/Footer";
import { Header } from "@/components/loyout/header/Header";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "../styles/globals.css";
import { Providers } from "./providers";

const inter = Nunito({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Testing Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
